Numpy is a fundamental library for scientific computing in python.It provides support for arrays and matrices,along with a collenction of mathematical functions to operate on these data structures.In this lesson, we will cover the basics of Numpy,focusing oon arrays and cectorized operations.

In [1]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## create array using numpy
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2=np.array([[1,2,3,4,5]])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [4]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
## identity mathrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Attributes of np
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("shape:",arr.shape) # output: (2,3)
print("Number of dimensions:",arr.ndim) # output: 2
print("Size (number of elements):",arr.size) #Output :6
print("Data Type:",arr.dtype) #Output: int64 (may vary based on platform)
print("Item size (in bytes):",arr.itemsize)# output: 8(may vary based on paltform)

Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data Type: int64
Item size (in bytes): 8


In [12]:
## Numpy Vectorized Operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Elements wise addition
print("Addition:",arr1+arr2)

## Element wisse substration
print("Substraction:",arr1-arr2)

## Element wise multiplecation
print("Multiplecation", arr1*arr2)

## Element wise division
print("Division:", arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplecation [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [14]:
## Universal Function

arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))  # Output: [1.41421356 1.732050

## Exponential
print(np.exp(arr))

##sine
print(np.sin(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
